"""Real-Debrid / AllDebrid link resolution.

Cove keeps the original hoster URL as the identity of a download. This
module turns that URL into a short-lived direct URL on the provider's
delivery node, which is handed straight to aria2 and then forgotten.

Two rules drive the whole design:

1. The generated node URL and the API credentials are secrets. They never
   appear in an exception, a log line, the database, or the UI. Every
   error raised here carries a fixed, human-readable sentence chosen by
   Cove — provider-supplied text is deliberately never echoed, because a
   provider is free to include the submitted link (and its query secrets)
   in its own message.
2. When no configured provider claims a host, resolution returns None and
   Cove downloads the URL directly, exactly as it always has.

Deliberately out of scope for this slice: torrents/magnets, folder and
container links, streaming-quality selection, AllDebrid redirectors, and
account-bound share/landing links generated by someone else's account.

This module is intentionally Qt-free so it can be exercised without a
running event loop; the queue calls it from a background worker.
"""
from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

import requests

from .config import (
    DEBRID_ALL_DEBRID,
    DEBRID_DEFAULT_PROVIDER,
    DEBRID_PROVIDERS,
    DEBRID_REAL_DEBRID,
)

REAL_DEBRID = DEBRID_REAL_DEBRID
ALL_DEBRID = DEBRID_ALL_DEBRID
PROVIDERS = DEBRID_PROVIDERS
PROVIDER_LABELS = {REAL_DEBRID: "Real-Debrid", ALL_DEBRID: "AllDebrid"}

RD_BASE = "https://api.real-debrid.com/rest/1.0"
AD_BASE = "https://api.alldebrid.com/v4"

# (connect, read). Generous on read because unlock can be slow under load.
HTTP_TIMEOUT = (10, 30)

HOST_CACHE_FILE = "debrid_hosts.json"
HOST_CACHE_TTL = 24 * 60 * 60

# AllDebrid asks callers to poll a delayed link no faster than every five
# seconds. The deadline keeps a stuck generation from pinning a worker.
DELAYED_POLL_INTERVAL = 5.0
DELAYED_MAX_WAIT = 60.0

# Provider-owned domains. A URL on one of these is either already a
# generated node link or an account-bound landing page; re-resolving it
# would fail or silently produce someone else's download, so Cove leaves
# it on the normal direct path.
PROVIDER_OWN_DOMAINS = (
    "real-debrid.com",
    "alldebrid.com",
    "debrid.it",
)


@dataclass
class Unrestricted:
    """A resolved, ready-to-download link. `download` is a secret."""

    download: str
    filename: str
    filesize: int
    provider: str


class DebridError(Exception):
    """A provider failure, already reduced to something safe to display.

    `user_message` is always one of Cove's own fixed strings. Nothing
    derived from the request (credential, submitted link) or the response
    (provider message, generated URL) is ever folded into it.
    """

    def __init__(
        self,
        provider: str,
        code,
        user_message: str,
        fallback_allowed: bool = False,
        host_unsupported: bool = False,
    ):
        self.provider = provider
        self.code = code
        self.user_message = user_message
        self.fallback_allowed = fallback_allowed
        self.host_unsupported = host_unsupported
        super().__init__(f"{provider_label(provider)}: {user_message}")


def provider_label(provider: str) -> str:
    return PROVIDER_LABELS.get(provider, "Debrid")


# ---------------------------------------------------------------------------
# Error tables
# ---------------------------------------------------------------------------

# code -> (message, fallback_allowed, host_unsupported)
#
# Fallback is allowed only for conditions that are about *this provider's*
# relationship to the host (unsupported, saturated, rate limited, out of
# traffic) — the other provider may well succeed. It is never allowed for
# credential, account, or file-level failures, where a silent retry would
# either hide a real configuration problem from the user or produce the
# same result twice.
_RD_ERRORS = {
    8: ("the API token was rejected. Check the token in Settings.", False, False),
    9: ("this account is not permitted to unrestrict links.", False, False),
    14: ("this account is locked.", False, False),
    16: ("this host is not supported.", True, True),
    17: ("this host is in maintenance.", True, False),
    18: ("the download limit for this host has been reached.", True, False),
    19: ("this host is temporarily unavailable.", True, False),
    20: ("this host requires a premium account.", False, False),
    21: ("too many downloads are already active on this account.", True, False),
    23: ("the traffic allowance for this host is exhausted.", True, False),
    24: ("the file is unavailable on the host.", False, False),
    25: ("the service is temporarily unavailable.", True, False),
    34: ("too many requests. Wait a moment and try again.", True, False),
    35: ("the file was refused as infringing.", False, False),
    36: ("the fair-usage limit for this account has been reached.", True, False),
}

_AD_ERRORS = {
    "AUTH_MISSING_APIKEY": ("no API key was sent. Check the key in Settings.", False, False),
    "AUTH_BAD_APIKEY": ("the API key was rejected. Check the key in Settings.", False, False),
    "AUTH_BLOCKED": ("this API key is blocked.", False, False),
    "AUTH_USER_BANNED": ("this account is banned.", False, False),
    "MAINTENANCE": ("the service is in maintenance.", True, False),
    "NO_SERVER": ("no download server is available for this link.", False, False),
    "LINK_HOST_NOT_SUPPORTED": ("this host is not supported.", True, True),
    "LINK_NOT_SUPPORTED": ("this link is not supported.", True, True),
    "LINK_DOWN": ("the file is no longer available on the host.", False, False),
    "LINK_HOST_UNAVAILABLE": ("this host is temporarily unavailable.", True, False),
    "LINK_TOO_MANY_DOWNLOADS": ("too many downloads are already active on this account.", True, False),
    "LINK_HOST_FULL": ("the host's servers are full.", True, False),
    "LINK_HOST_LIMIT_REACHED": ("the download limit for this host has been reached.", True, False),
    "LINK_TEMPORARY_UNAVAILABLE": ("this link is temporarily unavailable.", True, False),
    "LINK_PASS_PROTECTED": ("this link is password protected, which Cove does not support yet.", False, False),
    "LINK_ERROR": ("the link could not be unlocked.", False, False),
    "MUST_BE_PREMIUM": ("this host requires a premium account.", False, False),
    "FREE_TRIAL_LIMIT_REACHED": ("the free trial limit has been reached.", False, False),
    "DELAYED_INVALID_ID": ("the delayed link reference expired before the file was ready.", False, False),
}

_UNKNOWN = ("the request failed for an unrecognised reason.", False, False)
_BAD_RESPONSE = "the response could not be understood."
_TRANSPORT = "could not be reached."


def _error(provider: str, code, table: dict) -> DebridError:
    message, fallback, unsupported = table.get(code, _UNKNOWN)
    return DebridError(provider, code, message, fallback, unsupported)


def _bad_response(provider: str) -> DebridError:
    return DebridError(provider, "bad_response", _BAD_RESPONSE, False, False)


# ---------------------------------------------------------------------------
# HTTP plumbing
# ---------------------------------------------------------------------------


def _session(session):
    return requests if session is None else session


def _request(session, method: str, url: str, provider: str, *, headers=None, data=None):
    """Issue one bounded request. Transport failures become DebridError.

    Nothing about the request is logged; the caller only ever sees the
    fixed provider-named sentence.
    """
    call = getattr(_session(session), method)
    try:
        return call(url, headers=headers, data=data, timeout=HTTP_TIMEOUT)
    except Exception:
        raise DebridError(provider, "transport", _TRANSPORT, True, False) from None


def _json_body(resp, provider: str):
    try:
        return resp.json()
    except Exception:
        raise _bad_response(provider) from None


def _bearer(credential: str) -> dict:
    return {"Authorization": f"Bearer {credential}"}


def _safe_download_url(value, provider: str) -> str:
    """Accept only an http(s) URL. Rejection text never quotes the value."""
    if not isinstance(value, str) or not value:
        raise _bad_response(provider)
    try:
        scheme = urlparse(value).scheme.lower()
    except ValueError:
        raise _bad_response(provider) from None
    if scheme not in ("http", "https"):
        raise DebridError(
            provider, "unsafe_url",
            "returned a link Cove will not download from.", False, False,
        )
    return value


# Mirrors api_server.validate_filename, which is the canonical definition of
# a filename Cove considers safe. It is deliberately not imported here: that
# module pulls in the HTTP server, and cove.debrid is kept Qt-free and
# import-light. tests/test_debrid.py asserts the two rule sets agree.
_FILENAME_RESERVED_CHARS = '/\\:<>"|?*'
_WINDOWS_RESERVED_NAMES = frozenset(
    ("CON", "PRN", "AUX", "NUL")
    + tuple(f"COM{i}" for i in range(1, 10))
    + tuple(f"LPT{i}" for i in range(1, 10))
)


def _safe_filename(value) -> str:
    """Reduce a provider-supplied filename to something Cove will accept.

    Provider filenames are untrusted input and reach aria2 as the output
    name, so they must clear the same bar as a filename submitted through
    the local API. Anything that can't be made to clear it returns "",
    which simply means "no name" — aria2 then derives one itself and the
    download still runs. Rejecting the whole download over a bad name
    would be a worse outcome than letting aria2 name the file.
    """
    if not isinstance(value, str):
        return ""
    # Keep only the basename: the provider must never steer the write path.
    name = value.replace("\\", "/").rsplit("/", 1)[-1]
    name = "".join(c for c in name if ord(c) >= 32 and ord(c) != 127)
    # Windows rejects trailing spaces and periods outright.
    name = name.strip().rstrip(" .")
    if not name or len(name) > 255:
        return ""
    if any(char in name for char in _FILENAME_RESERVED_CHARS):
        return ""
    if name.split(".", 1)[0].upper() in _WINDOWS_RESERVED_NAMES:
        return ""
    return name


def _safe_filesize(value, provider: str) -> int:
    if value is None:
        return 0
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise _bad_response(provider)
    size = int(value)
    if size < 0:
        raise _bad_response(provider)
    return size


# ---------------------------------------------------------------------------
# Real-Debrid
# ---------------------------------------------------------------------------


def _rd_payload(resp, provider=REAL_DEBRID):
    """Provider error envelopes are checked before the HTTP status, because
    Real-Debrid returns its useful error codes alongside a 4xx."""
    body = _json_body(resp, provider)
    if isinstance(body, dict) and ("error_code" in body or "error" in body):
        code = body.get("error_code")
        if not isinstance(code, int) or isinstance(code, bool):
            code = None
        raise _error(provider, code, _RD_ERRORS)
    if not 200 <= getattr(resp, "status_code", 0) < 300:
        raise DebridError(provider, "http", _TRANSPORT, True, False)
    return body


def real_debrid_unrestrict(link: str, token: str, *, session=None) -> Unrestricted:
    resp = _request(
        session, "post", f"{RD_BASE}/unrestrict/link", REAL_DEBRID,
        headers=_bearer(token), data={"link": link},
    )
    body = _rd_payload(resp)
    if not isinstance(body, dict):
        raise _bad_response(REAL_DEBRID)
    return Unrestricted(
        download=_safe_download_url(body.get("download"), REAL_DEBRID),
        filename=_safe_filename(body.get("filename")),
        filesize=_safe_filesize(body.get("filesize"), REAL_DEBRID),
        provider=REAL_DEBRID,
    )


def real_debrid_account(token: str, *, session=None) -> dict:
    """Sanitized account summary for the Settings "Test" button."""
    resp = _request(session, "get", f"{RD_BASE}/user", REAL_DEBRID, headers=_bearer(token))
    body = _rd_payload(resp)
    if not isinstance(body, dict):
        raise _bad_response(REAL_DEBRID)
    account = {"username": body.get("username") if isinstance(body.get("username"), str) else ""}
    if isinstance(body.get("type"), str):
        account["type"] = body["type"]
    if isinstance(body.get("expiration"), str):
        account["expiration"] = body["expiration"]
    return account


def real_debrid_supported_domains(*, session=None) -> list[str]:
    resp = _request(session, "get", f"{RD_BASE}/hosts/domains", REAL_DEBRID)
    body = _rd_payload(resp)
    if not isinstance(body, list):
        raise _bad_response(REAL_DEBRID)
    return _normalize_domains(body)


# ---------------------------------------------------------------------------
# AllDebrid
# ---------------------------------------------------------------------------


def _ad_data(resp) -> dict:
    """Unwrap the AllDebrid {status, data|error} envelope."""
    body = _json_body(resp, ALL_DEBRID)
    if not isinstance(body, dict):
        raise _bad_response(ALL_DEBRID)
    if body.get("status") == "error":
        error = body.get("error")
        code = error.get("code") if isinstance(error, dict) else None
        if not isinstance(code, str):
            code = None
        raise _error(ALL_DEBRID, code, _AD_ERRORS)
    if body.get("status") != "success":
        raise _bad_response(ALL_DEBRID)
    data = body.get("data")
    if not isinstance(data, dict):
        raise _bad_response(ALL_DEBRID)
    return data


def _ad_call(session, method: str, path: str, apikey: str | None = None, data=None) -> dict:
    resp = _request(
        session, method, f"{AD_BASE}{path}", ALL_DEBRID,
        headers=_bearer(apikey) if apikey is not None else None,
        data=data,
    )
    return _ad_data(resp)


def all_debrid_unrestrict(
    link: str,
    apikey: str,
    *,
    session=None,
    sleep=time.sleep,
    clock=time.monotonic,
) -> Unrestricted:
    data = _ad_call(session, "post", "/link/unlock", apikey, {"link": link})
    filename = _safe_filename(data.get("filename"))
    filesize = _safe_filesize(data.get("filesize"), ALL_DEBRID)

    raw_link = data.get("link")
    if isinstance(raw_link, str) and raw_link:
        return Unrestricted(
            download=_safe_download_url(raw_link, ALL_DEBRID),
            filename=filename,
            filesize=filesize,
            provider=ALL_DEBRID,
        )

    delayed = data.get("delayed")
    if isinstance(delayed, bool) or not isinstance(delayed, (int, str)) or delayed in ("", 0):
        raise _bad_response(ALL_DEBRID)

    download = _await_delayed(delayed, apikey, session=session, sleep=sleep, clock=clock)
    # The delayed endpoint only returns the final link, so the name and size
    # from the unlock response are what the queue gets to work with.
    return Unrestricted(
        download=download,
        filename=filename,
        filesize=filesize,
        provider=ALL_DEBRID,
    )


def _await_delayed(delayed_id, apikey: str, *, session, sleep, clock) -> str:
    """Poll /link/delayed until the node link exists, or give up.

    Always sleeps before the first poll (the link is by definition not
    ready yet) and never polls faster than DELAYED_POLL_INTERVAL.
    """
    deadline = clock() + DELAYED_MAX_WAIT
    while True:
        sleep(DELAYED_POLL_INTERVAL)
        data = _ad_call(session, "post", "/link/delayed", apikey, {"id": delayed_id})
        status = data.get("status")
        if isinstance(status, bool) or not isinstance(status, int):
            raise _bad_response(ALL_DEBRID)
        if status == 2:
            return _safe_download_url(data.get("link"), ALL_DEBRID)
        if status == 3:
            raise DebridError(
                ALL_DEBRID, "delayed_failed",
                "could not generate a download link for this file.", False, False,
            )
        if status != 1:
            raise _bad_response(ALL_DEBRID)
        if clock() >= deadline:
            raise DebridError(
                ALL_DEBRID, "delayed_timeout",
                "took too long to prepare this download link. Try again shortly.",
                False, False,
            )


def all_debrid_account(apikey: str, *, session=None) -> dict:
    data = _ad_call(session, "get", "/user", apikey)
    user = data.get("user")
    if not isinstance(user, dict):
        raise _bad_response(ALL_DEBRID)
    account = {"username": user.get("username") if isinstance(user.get("username"), str) else ""}
    if isinstance(user.get("isPremium"), bool):
        account["is_premium"] = user["isPremium"]
    if isinstance(user.get("isTrial"), bool):
        account["is_trial"] = user["isTrial"]
    premium_until = user.get("premiumUntil")
    if isinstance(premium_until, int) and not isinstance(premium_until, bool):
        account["premium_until"] = premium_until
    return account


def all_debrid_supported_domains(*, session=None) -> list[str]:
    # The domains endpoint is public, so no key is sent. Only `hosts` is
    # used: streams and redirectors are out of scope for this slice.
    data = _ad_call(session, "get", "/hosts/domains")
    hosts = data.get("hosts")
    if not isinstance(hosts, list):
        raise _bad_response(ALL_DEBRID)
    return _normalize_domains(hosts)


# ---------------------------------------------------------------------------
# Host matching and the domain cache
# ---------------------------------------------------------------------------


def _normalize_domains(values) -> list[str]:
    out = []
    seen = set()
    for value in values:
        if not isinstance(value, str):
            continue
        domain = value.strip().lower().strip(".")
        if not domain or domain in seen:
            continue
        seen.add(domain)
        out.append(domain)
    return out


def _hostname(url) -> str:
    """Hostname of an http(s) URL, or "" for anything else.

    Parsing rather than string matching is the point here: it is what
    keeps `rapidgator.net.evil.com` and `?x=rapidgator.net` from matching.
    """
    if not isinstance(url, str) or not url:
        return ""
    try:
        parsed = urlparse(url)
    except ValueError:
        return ""
    if parsed.scheme.lower() not in ("http", "https"):
        return ""
    return (parsed.hostname or "").lower().strip(".")


def is_supported_domain(url, domains) -> bool:
    """Exact host match, or a subdomain on a dot boundary."""
    host = _hostname(url)
    if not host or not domains:
        return False
    for domain in domains:
        if not isinstance(domain, str):
            continue
        domain = domain.strip().lower().strip(".")
        if domain and (host == domain or host.endswith("." + domain)):
            return True
    return False


def is_provider_domain(url) -> bool:
    return is_supported_domain(url, PROVIDER_OWN_DOMAINS)


def _cache_path() -> Path:
    from .config import DATA_DIR

    return Path(DATA_DIR) / HOST_CACHE_FILE


def _read_cache() -> dict:
    try:
        raw = json.loads(_cache_path().read_text())
    except (OSError, ValueError):
        return {}
    return raw if isinstance(raw, dict) else {}


def _cached_entry(cache: dict, provider: str):
    """Return (domains, fetched_at) for a usable entry, else (None, 0.0)."""
    entry = cache.get(provider)
    if not isinstance(entry, dict):
        return None, 0.0
    domains = entry.get("domains")
    if not isinstance(domains, list):
        return None, 0.0
    fetched_at = entry.get("fetched_at")
    if isinstance(fetched_at, bool) or not isinstance(fetched_at, (int, float)):
        fetched_at = 0.0
    return _normalize_domains(domains), float(fetched_at)


def _write_cache(provider: str, domains: list[str]) -> None:
    cache = _read_cache()
    cache[provider] = {"fetched_at": time.time(), "domains": domains}
    path = _cache_path()
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(cache))
        tmp.replace(path)
    except OSError:
        # A cache we cannot write is not worth failing a download over.
        pass


def supported_domains(provider: str, *, session=None, now=None) -> Optional[list[str]]:
    """Cached host list for a provider.

    Returns None when neither a cache nor a live fetch is available. The
    caller must read that as "unknown, treat the URL as a candidate" and
    let the resolve endpoint decide, rather than as "unsupported".
    """
    now = time.time() if now is None else now
    cached, fetched_at = _cached_entry(_read_cache(), provider)
    if cached is not None and 0 <= now - fetched_at < HOST_CACHE_TTL:
        return cached
    fetch = (
        all_debrid_supported_domains if provider == ALL_DEBRID
        else real_debrid_supported_domains
    )
    try:
        domains = fetch(session=session)
    except Exception:
        return cached  # stale list if we have one, else None
    _write_cache(provider, domains)
    return domains


# ---------------------------------------------------------------------------
# Shared resolver
# ---------------------------------------------------------------------------


def _preferred(settings) -> str:
    preferred = getattr(settings, "debrid_preferred_provider", DEBRID_DEFAULT_PROVIDER)
    return preferred if preferred in PROVIDERS else DEBRID_DEFAULT_PROVIDER


def _enabled_providers(settings) -> list[tuple[str, str]]:
    """(provider, credential) pairs, preferred provider first."""
    pairs = []
    if getattr(settings, "all_debrid_enabled", False) is True:
        pairs.append((ALL_DEBRID, getattr(settings, "all_debrid_api_key", "")))
    if getattr(settings, "real_debrid_enabled", False) is True:
        pairs.append((REAL_DEBRID, getattr(settings, "real_debrid_api_token", "")))
    preferred = _preferred(settings)
    pairs.sort(key=lambda pair: 0 if pair[0] == preferred else 1)
    return pairs


def is_enabled(settings) -> bool:
    """True when the user has switched on at least one provider.

    The queue uses this to decide whether an http(s) task must go through
    the resolving worker. It deliberately ignores whether a credential is
    present: an enabled provider with an empty key has to reach resolve()
    so the user gets the "no API key saved" error, rather than silently
    getting a free-tier download from the hoster instead.
    """
    return bool(_enabled_providers(settings))


def _unrestrict(provider: str, url: str, credential: str, *, session, sleep, clock):
    if provider == ALL_DEBRID:
        return all_debrid_unrestrict(
            url, credential, session=session, sleep=sleep, clock=clock
        )
    return real_debrid_unrestrict(url, credential, session=session)


def resolve(
    url: str,
    settings,
    *,
    session=None,
    sleep=time.sleep,
    clock=time.monotonic,
) -> Optional[Unrestricted]:
    """Resolve `url` through the configured providers.

    Returns None when debrid does not apply — nothing enabled, not an
    http(s) URL, a provider-owned URL, or no enabled provider supports the
    host. In every one of those cases Cove downloads the URL directly.

    Raises DebridError when a provider that should have handled the link
    failed in a way the user needs to know about.
    """
    if not _hostname(url) or is_provider_domain(url):
        return None
    providers = _enabled_providers(settings)
    if not providers:
        return None

    errors: list[DebridError] = []
    for provider, credential in providers:
        domains = supported_domains(provider, session=session)
        if domains is not None and not is_supported_domain(url, domains):
            # This provider publishes a host list and this host isn't on
            # it; don't spend a request asking.
            continue
        if not isinstance(credential, str) or not credential.strip():
            raise DebridError(
                provider, "missing_credential",
                "is enabled but has no API key saved. Add one in Settings.",
                False, False,
            )
        try:
            return _unrestrict(
                provider, url, credential.strip(),
                session=session, sleep=sleep, clock=clock,
            )
        except DebridError as exc:
            if not exc.fallback_allowed:
                raise
            errors.append(exc)

    if errors and not all(exc.host_unsupported for exc in errors):
        # Something recoverable-looking went wrong everywhere. Surface the
        # last reason rather than quietly downloading the free-tier page.
        raise errors[-1]
    return None
