"""Real-Debrid / AllDebrid link resolution.

Cove keeps the original hoster URL as the identity of a download. This
module turns that URL into a short-lived direct URL on the provider's
delivery node, which is handed straight to aria2 and then forgotten.

Two rules drive the whole design:

1. The generated node URL and the API credentials are secrets. They never
   appear in an exception, a log line, the database, or the UI. Every
   error raised here carries a fixed, human-readable sentence chosen by
   Cove — provider-supplied text is deliberately never echoed, because a
   provider is free to include the submitted link (and its query secrets)
   in its own message.
2. When no configured provider claims a host, resolution returns None and
   Cove downloads the URL directly, exactly as it always has.

Cached torrents (see the section at the foot of this module) reuse the same
rules with one twist: a torrent file's account-bound *locked* link is
stable, so it is persisted as the task's identity and unlocked into a node
URL on every launch, exactly as a hoster link would be.

Deliberately out of scope for this slice: folder and container links,
streaming-quality selection, AllDebrid redirectors, account-bound
share/landing links generated by someone else's account, and asking a
provider to fetch a torrent it does not already hold.

This module is intentionally Qt-free so it can be exercised without a
running event loop; the queue calls it from a background worker.
"""
from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

import requests

from . import torrent as _torrent
from .config import (
    DEBRID_ALL_DEBRID,
    DEBRID_DEFAULT_PROVIDER,
    DEBRID_PROVIDERS,
    DEBRID_REAL_DEBRID,
    DEBRID_TORBOX,
)

REAL_DEBRID = DEBRID_REAL_DEBRID
ALL_DEBRID = DEBRID_ALL_DEBRID
TORBOX = DEBRID_TORBOX
PROVIDERS = DEBRID_PROVIDERS
PROVIDER_LABELS = {REAL_DEBRID: "Real-Debrid", ALL_DEBRID: "AllDebrid", TORBOX: "TorBox"}

# TorBox is Cove's third debrid provider. Its complete feature (ordinary
# hoster downloads plus cached-torrent routing) ships across two slices;
# this flag stays False until both have landed, so a user on a T1 build
# never sees a half-finished provider. Tests may monkeypatch this module
# attribute to True to exercise the gated code paths; it is not a Settings
# field because it describes what Cove ships, not what the user chose.
TORBOX_FEATURE_AVAILABLE = True

RD_BASE = "https://api.real-debrid.com/rest/1.0"
AD_BASE = "https://api.alldebrid.com/v4"
TORBOX_BASE = "https://api.torbox.app/v1/api"
TORBOX_READY_POLL_INTERVAL = 1.0
TORBOX_READY_MAX_WAIT = 10.0

# (connect, read). Generous on read because unlock can be slow under load.
HTTP_TIMEOUT = (10, 30)

HOST_CACHE_FILE = "debrid_hosts.json"
HOST_CACHE_TTL = 24 * 60 * 60

# AllDebrid asks callers to poll a delayed link no faster than every five
# seconds. The deadline keeps a stuck generation from pinning a worker.
DELAYED_POLL_INTERVAL = 5.0
DELAYED_MAX_WAIT = 60.0

# Provider-owned domains. A URL on one of these is either already a
# generated node link or an account-bound landing page; re-resolving it
# would fail or silently produce someone else's download, so Cove leaves
# it on the normal direct path.
PROVIDER_OWN_DOMAINS = (
    "real-debrid.com",
    "alldebrid.com",
    "debrid.it",
    "torbox.app",
)


@dataclass
class Unrestricted:
    """A resolved, ready-to-download link. `download` is a secret."""

    download: str
    filename: str
    filesize: int
    provider: str
    # TorBox only: the web-download (T1) or torrent (T2) item ID the queue
    # persists so a retry/restart can reuse it instead of creating another
    # one. Empty for AllDebrid/Real-Debrid, which have no such identity.
    item_id: str = ""


class DebridError(Exception):
    """A provider failure, already reduced to something safe to display.

    `user_message` is always one of Cove's own fixed strings. Nothing
    derived from the request (credential, submitted link) or the response
    (provider message, generated URL) is ever folded into it.
    """

    def __init__(
        self,
        provider: str,
        code,
        user_message: str,
        fallback_allowed: bool = False,
        host_unsupported: bool = False,
    ):
        self.provider = provider
        self.code = code
        self.user_message = user_message
        self.fallback_allowed = fallback_allowed
        self.host_unsupported = host_unsupported
        super().__init__(f"{provider_label(provider)}: {user_message}")


def provider_label(provider: str) -> str:
    return PROVIDER_LABELS.get(provider, "Debrid")


# ---------------------------------------------------------------------------
# Error tables
# ---------------------------------------------------------------------------

# code -> (message, fallback_allowed, host_unsupported)
#
# Fallback is allowed only for conditions that are about *this provider's*
# relationship to the host (unsupported, saturated, rate limited, out of
# traffic) — the other provider may well succeed. It is never allowed for
# credential, account, or file-level failures, where a silent retry would
# either hide a real configuration problem from the user or produce the
# same result twice.
_RD_ERRORS = {
    8: ("the API token was rejected. Check the token in Settings.", False, False),
    9: ("this account is not permitted to unrestrict links.", False, False),
    14: ("this account is locked.", False, False),
    16: ("this host is not supported.", True, True),
    17: ("this host is in maintenance.", True, False),
    18: ("the download limit for this host has been reached.", True, False),
    19: ("this host is temporarily unavailable.", True, False),
    20: ("this host requires a premium account.", False, False),
    21: ("too many downloads are already active on this account.", True, False),
    23: ("the traffic allowance for this host is exhausted.", True, False),
    24: ("the file is unavailable on the host.", False, False),
    25: ("the service is temporarily unavailable.", True, False),
    34: ("too many requests. Wait a moment and try again.", True, False),
    35: ("the file was refused as infringing.", False, False),
    36: ("the fair-usage limit for this account has been reached.", True, False),
}

_AD_ERRORS = {
    "AUTH_MISSING_APIKEY": ("no API key was sent. Check the key in Settings.", False, False),
    "AUTH_BAD_APIKEY": ("the API key was rejected. Check the key in Settings.", False, False),
    "AUTH_BLOCKED": ("this API key is blocked.", False, False),
    "AUTH_USER_BANNED": ("this account is banned.", False, False),
    "MAINTENANCE": ("the service is in maintenance.", True, False),
    "NO_SERVER": ("no download server is available for this link.", False, False),
    "LINK_HOST_NOT_SUPPORTED": ("this host is not supported.", True, True),
    "LINK_NOT_SUPPORTED": ("this link is not supported.", True, True),
    "LINK_DOWN": ("the file is no longer available on the host.", False, False),
    "LINK_HOST_UNAVAILABLE": ("this host is temporarily unavailable.", True, False),
    "LINK_TOO_MANY_DOWNLOADS": ("too many downloads are already active on this account.", True, False),
    "LINK_HOST_FULL": ("the host's servers are full.", True, False),
    "LINK_HOST_LIMIT_REACHED": ("the download limit for this host has been reached.", True, False),
    "LINK_TEMPORARY_UNAVAILABLE": ("this link is temporarily unavailable.", True, False),
    "LINK_PASS_PROTECTED": ("this link is password protected, which Cove does not support yet.", False, False),
    "LINK_ERROR": ("the link could not be unlocked.", False, False),
    "MUST_BE_PREMIUM": ("this host requires a premium account.", False, False),
    "FREE_TRIAL_LIMIT_REACHED": ("the free trial limit has been reached.", False, False),
    "DELAYED_INVALID_ID": ("the delayed link reference expired before the file was ready.", False, False),
}

_UNKNOWN = ("the request failed for an unrecognised reason.", False, False)
_BAD_RESPONSE = "the response could not be understood."
_TRANSPORT = "could not be reached."


def _error(provider: str, code, table: dict) -> DebridError:
    message, fallback, unsupported = table.get(code, _UNKNOWN)
    return DebridError(provider, code, message, fallback, unsupported)


def _bad_response(provider: str) -> DebridError:
    return DebridError(provider, "bad_response", _BAD_RESPONSE, False, False)


# ---------------------------------------------------------------------------
# HTTP plumbing
# ---------------------------------------------------------------------------


def _session(session):
    return requests if session is None else session


def _request(session, method: str, url: str, provider: str, *, headers=None, data=None, files=None):
    """Issue one bounded request. Transport failures become DebridError.

    Nothing about the request is logged; the caller only ever sees the
    fixed provider-named sentence.
    """
    call = getattr(_session(session), method)
    kwargs = {"headers": headers, "data": data, "timeout": HTTP_TIMEOUT}
    if files is not None:
        # Only multipart uploads pass this; keeping it out of the common
        # case means the existing call shape is untouched.
        kwargs["files"] = files
    try:
        return call(url, **kwargs)
    except Exception:
        raise DebridError(provider, "transport", _TRANSPORT, True, False) from None


def _json_body(resp, provider: str):
    try:
        return resp.json()
    except Exception:
        raise _bad_response(provider) from None


def _bearer(credential: str) -> dict:
    return {"Authorization": f"Bearer {credential}"}


def _safe_download_url(value, provider: str) -> str:
    """Accept only an http(s) URL. Rejection text never quotes the value."""
    if not isinstance(value, str) or not value:
        raise _bad_response(provider)
    try:
        scheme = urlparse(value).scheme.lower()
    except ValueError:
        raise _bad_response(provider) from None
    if scheme not in ("http", "https"):
        raise DebridError(
            provider, "unsafe_url",
            "returned a link Cove will not download from.", False, False,
        )
    return value


# Mirrors api_server.validate_filename, which is the canonical definition of
# a filename Cove considers safe. It is deliberately not imported here: that
# module pulls in the HTTP server, and cove.debrid is kept Qt-free and
# import-light. tests/test_debrid.py asserts the two rule sets agree.
_FILENAME_RESERVED_CHARS = '/\\:<>"|?*'
_WINDOWS_RESERVED_NAMES = frozenset(
    ("CON", "PRN", "AUX", "NUL")
    + tuple(f"COM{i}" for i in range(1, 10))
    + tuple(f"LPT{i}" for i in range(1, 10))
)


def _safe_filename(value) -> str:
    """Reduce a provider-supplied filename to something Cove will accept.

    Provider filenames are untrusted input and reach aria2 as the output
    name, so they must clear the same bar as a filename submitted through
    the local API. Anything that can't be made to clear it returns "",
    which simply means "no name" — aria2 then derives one itself and the
    download still runs. Rejecting the whole download over a bad name
    would be a worse outcome than letting aria2 name the file.
    """
    if not isinstance(value, str):
        return ""
    # Keep only the basename: the provider must never steer the write path.
    name = value.replace("\\", "/").rsplit("/", 1)[-1]
    name = "".join(c for c in name if ord(c) >= 32 and ord(c) != 127)
    # Windows rejects trailing spaces and periods outright.
    name = name.strip().rstrip(" .")
    if not name or len(name) > 255:
        return ""
    if any(char in name for char in _FILENAME_RESERVED_CHARS):
        return ""
    if name.split(".", 1)[0].upper() in _WINDOWS_RESERVED_NAMES:
        return ""
    return name


def _safe_filesize(value, provider: str) -> int:
    if value is None:
        return 0
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise _bad_response(provider)
    size = int(value)
    if size < 0:
        raise _bad_response(provider)
    return size


# ---------------------------------------------------------------------------
# Real-Debrid
# ---------------------------------------------------------------------------


def _rd_payload(resp, provider=REAL_DEBRID):
    """Provider error envelopes are checked before the HTTP status, because
    Real-Debrid returns its useful error codes alongside a 4xx."""
    body = _json_body(resp, provider)
    if isinstance(body, dict) and ("error_code" in body or "error" in body):
        code = body.get("error_code")
        if not isinstance(code, int) or isinstance(code, bool):
            code = None
        raise _error(provider, code, _RD_ERRORS)
    if not 200 <= getattr(resp, "status_code", 0) < 300:
        raise DebridError(provider, "http", _TRANSPORT, True, False)
    return body


def real_debrid_unrestrict(link: str, token: str, *, session=None) -> Unrestricted:
    resp = _request(
        session, "post", f"{RD_BASE}/unrestrict/link", REAL_DEBRID,
        headers=_bearer(token), data={"link": link},
    )
    body = _rd_payload(resp)
    if not isinstance(body, dict):
        raise _bad_response(REAL_DEBRID)
    return Unrestricted(
        download=_safe_download_url(body.get("download"), REAL_DEBRID),
        filename=_safe_filename(body.get("filename")),
        filesize=_safe_filesize(body.get("filesize"), REAL_DEBRID),
        provider=REAL_DEBRID,
    )


def real_debrid_account(token: str, *, session=None) -> dict:
    """Sanitized account summary for the Settings "Test" button."""
    resp = _request(session, "get", f"{RD_BASE}/user", REAL_DEBRID, headers=_bearer(token))
    body = _rd_payload(resp)
    if not isinstance(body, dict):
        raise _bad_response(REAL_DEBRID)
    account = {"username": body.get("username") if isinstance(body.get("username"), str) else ""}
    if isinstance(body.get("type"), str):
        account["type"] = body["type"]
    if isinstance(body.get("expiration"), str):
        account["expiration"] = body["expiration"]
    return account


def real_debrid_supported_domains(*, session=None) -> list[str]:
    resp = _request(session, "get", f"{RD_BASE}/hosts/domains", REAL_DEBRID)
    body = _rd_payload(resp)
    if not isinstance(body, list):
        raise _bad_response(REAL_DEBRID)
    return _normalize_domains(body)


# ---------------------------------------------------------------------------
# AllDebrid
# ---------------------------------------------------------------------------


def _ad_data(resp) -> dict:
    """Unwrap the AllDebrid {status, data|error} envelope."""
    body = _json_body(resp, ALL_DEBRID)
    if not isinstance(body, dict):
        raise _bad_response(ALL_DEBRID)
    if body.get("status") == "error":
        error = body.get("error")
        code = error.get("code") if isinstance(error, dict) else None
        if not isinstance(code, str):
            code = None
        raise _error(ALL_DEBRID, code, _AD_ERRORS)
    if body.get("status") != "success":
        raise _bad_response(ALL_DEBRID)
    data = body.get("data")
    if not isinstance(data, dict):
        raise _bad_response(ALL_DEBRID)
    return data


def _ad_call(session, method: str, path: str, apikey: str | None = None, data=None) -> dict:
    resp = _request(
        session, method, f"{AD_BASE}{path}", ALL_DEBRID,
        headers=_bearer(apikey) if apikey is not None else None,
        data=data,
    )
    return _ad_data(resp)


def all_debrid_unrestrict(
    link: str,
    apikey: str,
    *,
    session=None,
    sleep=time.sleep,
    clock=time.monotonic,
) -> Unrestricted:
    data = _ad_call(session, "post", "/link/unlock", apikey, {"link": link})
    filename = _safe_filename(data.get("filename"))
    filesize = _safe_filesize(data.get("filesize"), ALL_DEBRID)

    raw_link = data.get("link")
    if isinstance(raw_link, str) and raw_link:
        return Unrestricted(
            download=_safe_download_url(raw_link, ALL_DEBRID),
            filename=filename,
            filesize=filesize,
            provider=ALL_DEBRID,
        )

    delayed = data.get("delayed")
    if isinstance(delayed, bool) or not isinstance(delayed, (int, str)) or delayed in ("", 0):
        raise _bad_response(ALL_DEBRID)

    download = _await_delayed(delayed, apikey, session=session, sleep=sleep, clock=clock)
    # The delayed endpoint only returns the final link, so the name and size
    # from the unlock response are what the queue gets to work with.
    return Unrestricted(
        download=download,
        filename=filename,
        filesize=filesize,
        provider=ALL_DEBRID,
    )


def _await_delayed(delayed_id, apikey: str, *, session, sleep, clock) -> str:
    """Poll /link/delayed until the node link exists, or give up.

    Always sleeps before the first poll (the link is by definition not
    ready yet) and never polls faster than DELAYED_POLL_INTERVAL.
    """
    deadline = clock() + DELAYED_MAX_WAIT
    while True:
        sleep(DELAYED_POLL_INTERVAL)
        data = _ad_call(session, "post", "/link/delayed", apikey, {"id": delayed_id})
        status = data.get("status")
        if isinstance(status, bool) or not isinstance(status, int):
            raise _bad_response(ALL_DEBRID)
        if status == 2:
            return _safe_download_url(data.get("link"), ALL_DEBRID)
        if status == 3:
            raise DebridError(
                ALL_DEBRID, "delayed_failed",
                "could not generate a download link for this file.", False, False,
            )
        if status != 1:
            raise _bad_response(ALL_DEBRID)
        if clock() >= deadline:
            raise DebridError(
                ALL_DEBRID, "delayed_timeout",
                "took too long to prepare this download link. Try again shortly.",
                False, False,
            )


def all_debrid_account(apikey: str, *, session=None) -> dict:
    data = _ad_call(session, "get", "/user", apikey)
    user = data.get("user")
    if not isinstance(user, dict):
        raise _bad_response(ALL_DEBRID)
    account = {"username": user.get("username") if isinstance(user.get("username"), str) else ""}
    if isinstance(user.get("isPremium"), bool):
        account["is_premium"] = user["isPremium"]
    if isinstance(user.get("isTrial"), bool):
        account["is_trial"] = user["isTrial"]
    premium_until = user.get("premiumUntil")
    if isinstance(premium_until, int) and not isinstance(premium_until, bool):
        account["premium_until"] = premium_until
    return account


def all_debrid_supported_domains(*, session=None) -> list[str]:
    # The domains endpoint is public, so no key is sent. Only `hosts` is
    # used: streams and redirectors are out of scope for this slice.
    data = _ad_call(session, "get", "/hosts/domains")
    hosts = data.get("hosts")
    if not isinstance(hosts, list):
        raise _bad_response(ALL_DEBRID)
    return _normalize_domains(hosts)


# ---------------------------------------------------------------------------
# TorBox
# ---------------------------------------------------------------------------
#
# TorBox's official SDKs (torbox-sdk-py, torbox-sdk-dotnet) expose no
# "cached-only" parameter on createwebdownload -- unlike AllDebrid/Real-Debrid
# unrestrict, there is no server-side guarantee against creating an uncached
# cloud job. Cove enforces cached-only behaviour itself: it calls the
# separate GET /webdl/checkcached endpoint first and only creates a web
# download when that reports the link cached. Any ambiguous or unparseable
# checkcached response is treated as "not cached", never as "cached" -- a
# false negative just skips TorBox for this link, while a false positive
# would create an uncached job Cove promised never to leave running.
#
# Exact error-code casing for TorBox's `error` field is not part of any
# published SDK/schema, so error classification here is done by HTTP status
# only (401/403 auth, 429 rate limit, 5xx temporary), matching the responses
# tables above in spirit without guessing string values TorBox may or may
# not actually return.


def _torbox_error_for_status(status: int) -> DebridError:
    if status in (401, 403):
        return DebridError(
            TORBOX, "auth",
            "the API token was rejected. Check the token in Settings.",
            False, False,
        )
    if status == 429:
        return DebridError(
            TORBOX, "rate_limited",
            "too many requests. Wait a moment and try again.", True, False,
        )
    if 500 <= status < 600:
        return DebridError(TORBOX, "http", _TRANSPORT, True, False)
    return _error(TORBOX, "unknown", {})


def _torbox_payload(resp):
    """Unwrap the {success, error, detail, data} envelope and return `data`.

    Provider `detail`/`error` text is deliberately never read here: only
    the HTTP status decides which fixed Cove message is raised.
    """
    body = _json_body(resp, TORBOX)
    status = getattr(resp, "status_code", 0)
    if not isinstance(body, dict) or body.get("success") is not True:
        if not 200 <= status < 300:
            raise _torbox_error_for_status(status)
        raise _bad_response(TORBOX)
    if not 200 <= status < 300:
        raise _torbox_error_for_status(status)
    return body.get("data")


def torbox_account(token: str, *, session=None) -> dict:
    """Sanitized account summary for the Settings "Test" button."""
    resp = _request(session, "get", f"{TORBOX_BASE}/user/me", TORBOX, headers=_bearer(token))
    data = _torbox_payload(resp)
    if not isinstance(data, dict):
        raise _bad_response(TORBOX)
    account: dict = {}
    email = data.get("email")
    if isinstance(email, str) and email:
        account["email"] = email
    if isinstance(data.get("is_subscribed"), bool):
        account["is_subscribed"] = data["is_subscribed"]
    expires = data.get("premium_expires_at")
    if isinstance(expires, str) and expires:
        account["expiration"] = expires
    return account


def torbox_supported_domains(*, session=None) -> list[str]:
    resp = _request(session, "get", f"{TORBOX_BASE}/webdl/hosters", TORBOX)
    data = _torbox_payload(resp)
    if not isinstance(data, list):
        raise _bad_response(TORBOX)
    domains: list[str] = []
    for entry in data:
        if not isinstance(entry, dict) or entry.get("status") is not True:
            continue
        entry_domains = entry.get("domains")
        if isinstance(entry_domains, list):
            domains.extend(entry_domains)
    return _normalize_domains(domains)


def _torbox_numeric_id(value, provider: str = TORBOX) -> str:
    """Round-trip an item/file ID through int() before it reaches a URL.

    Defence in depth: these values are either freshly returned by TorBox or
    read back from our own DB column, but neither source should ever be
    trusted enough to interpolate directly into a request. TorBox's own
    schema types these IDs as JSON numbers (e.g. `900.0`), which `int()`
    on the raw string form rejects outright, so a whole-valued float is
    normalized first; a fractional or non-finite one (`inf`/`nan`, whose
    `is_integer()` is also False) still falls through to the same
    rejection as any other malformed value.
    """
    if isinstance(value, bool):
        raise _bad_response(provider)
    if isinstance(value, float):
        if not value.is_integer():
            raise _bad_response(provider)
        value = int(value)
    try:
        return str(int(str(value)))
    except (TypeError, ValueError):
        raise _bad_response(provider) from None


def _torbox_check_cached(link: str, token: str, *, session=None) -> bool:
    import hashlib

    digest = hashlib.md5(link.encode("utf-8")).hexdigest()
    resp = _request(
        session, "get", f"{TORBOX_BASE}/webdl/checkcached?hash={digest}", TORBOX,
        headers=_bearer(token),
    )
    data = _torbox_payload(resp)
    if isinstance(data, dict):
        return bool(data.get(digest))
    if isinstance(data, list):
        return len(data) > 0
    return False


def _torbox_create_web_download(link: str, token: str, *, session=None) -> str:
    resp = _request(
        session, "post", f"{TORBOX_BASE}/webdl/createwebdownload", TORBOX,
        headers=_bearer(token), files={"link": (None, link)},
    )
    data = _torbox_payload(resp)
    if not isinstance(data, dict):
        raise _bad_response(TORBOX)
    item_id = data.get("webdownload_id")
    if isinstance(item_id, bool) or not isinstance(item_id, (str, int)) or not str(item_id):
        raise _bad_response(TORBOX)
    return _torbox_numeric_id(item_id)


def _torbox_mylist_entry(item_id: str, token: str, *, session=None):
    """The mylist row for one web download, or None when TorBox has no
    record of it (a missing item, not an error)."""
    safe_id = _torbox_numeric_id(item_id)
    resp = _request(
        session, "get", f"{TORBOX_BASE}/webdl/mylist?id={safe_id}", TORBOX,
        headers=_bearer(token),
    )
    data = _torbox_payload(resp)
    if data is None:
        return None
    if isinstance(data, list):
        data = data[0] if data else None
    if data is not None and not isinstance(data, dict):
        raise _bad_response(TORBOX)
    return data


def _torbox_delete_web_download(item_id: str, token: str, *, session=None) -> None:
    """Best-effort cleanup for a job Cove's own polling decided to abandon.

    Never allowed to raise: this only ever runs while another DebridError is
    about to be raised, and a cleanup failure must not replace or hide it.
    """
    try:
        safe_id = _torbox_numeric_id(item_id)
        _request(
            session, "post", f"{TORBOX_BASE}/webdl/controlwebdownload", TORBOX,
            headers=_bearer(token), data={"id": safe_id, "operation": "delete"},
        )
    except DebridError:
        pass


def _torbox_pick_file(files, provider: str = TORBOX):
    if not isinstance(files, list) or not files:
        raise _bad_response(provider)
    first = files[0]
    if not isinstance(first, dict):
        raise _bad_response(provider)
    file_id = first.get("id")
    if isinstance(file_id, bool) or not isinstance(file_id, (str, int)) or not str(file_id):
        raise _bad_response(provider)
    return (
        _torbox_numeric_id(file_id, provider),
        _safe_filename(first.get("name")),
        _safe_filesize(first.get("size"), provider),
    )


def _torbox_request_dl(kind: str, item_id: str, file_id: str, token: str, *, session=None) -> str:
    """Generate a temporary TorBox delivery URL without ever leaking the
    tokenized request URL that produces it.

    TorBox's requestdl takes the API token as a query parameter, so the
    request URL itself is a secret. `allow_redirects=False` and the
    explicit `redirect=false` query flag both keep this call from ever
    silently following a redirect to that secret URL. Transport exceptions
    are deliberately reduced to a fixed message with `from None`: a
    requests.RequestException can quote the request URL (including the
    token) in its own text, and that text must never reach a DebridError,
    a log line, or a test failure snapshot.
    """
    from urllib.parse import urlencode

    id_param = "web_id" if kind == "webdl" else "torrent_id"
    query = urlencode({
        "token": token,
        id_param: _torbox_numeric_id(item_id),
        "file_id": _torbox_numeric_id(file_id),
        "redirect": "false",
    })
    url = f"{TORBOX_BASE}/{kind}/requestdl?{query}"
    try:
        resp = _session(session).get(url, timeout=HTTP_TIMEOUT, allow_redirects=False)
    except Exception:
        raise DebridError(TORBOX, "transport", _TRANSPORT, True, False) from None
    data = _torbox_payload(resp)
    return _safe_torbox_delivery_url(data)


def _safe_torbox_delivery_url(value) -> str:
    url = _safe_download_url(value, TORBOX)
    if is_supported_domain(url, ("api.torbox.app",)):
        # TorBox's own API/requestdl host echoed back as "data" would still
        # carry the token in its query string; refuse it as a delivery URL
        # rather than hand it to aria2. A CDN delivery host is expected to
        # live elsewhere (e.g. a *.torbox.app storage/CDN subdomain other
        # than api.), so only the API host itself is excluded here.
        raise DebridError(
            TORBOX, "unsafe_url",
            "returned a link Cove will not download from.", False, False,
        )
    try:
        parsed = urlparse(url)
    except ValueError:
        raise _bad_response(TORBOX) from None
    if parsed.username or parsed.password:
        raise DebridError(
            TORBOX, "unsafe_url",
            "returned a link Cove will not download from.", False, False,
        )
    return url


def torbox_unrestrict(
    link: str,
    token: str,
    *,
    session=None,
    sleep=time.sleep,
    clock=time.monotonic,
) -> Unrestricted:
    """First-time TorBox hoster route: cached-only create, then unlock.

    Never leaves an uncached job running: a bounded ready-poll that times
    out deletes the item it created before raising.
    """
    if not isinstance(token, str) or not token.strip():
        raise DebridError(
            TORBOX, "missing_credential",
            "is enabled but has no API token saved. Add one in Settings.",
            False, False,
        )
    token = token.strip()
    if not _torbox_check_cached(link, token, session=session):
        raise DebridError(
            TORBOX, "not_cached",
            "this file is not already available in your TorBox account.",
            True, True,
        )
    item_id = _torbox_create_web_download(link, token, session=session)
    deadline = clock() + TORBOX_READY_MAX_WAIT
    while True:
        entry = _torbox_mylist_entry(item_id, token, session=session)
        if entry is None:
            raise _bad_response(TORBOX)
        if entry.get("download_present") is True or entry.get("download_finished") is True:
            break
        if clock() >= deadline:
            _torbox_delete_web_download(item_id, token, session=session)
            raise DebridError(
                TORBOX, "not_ready",
                "could not confirm this download was ready in time.", True, True,
            )
        sleep(TORBOX_READY_POLL_INTERVAL)
    file_id, filename, filesize = _torbox_pick_file(entry.get("files"))
    download = _torbox_request_dl("webdl", item_id, file_id, token, session=session)
    return Unrestricted(
        download=download, filename=filename, filesize=filesize,
        provider=TORBOX, item_id=item_id,
    )


def torbox_refresh_web_download(
    item_id: str,
    hoster_url: str,
    settings,
    *,
    session=None,
    sleep=time.sleep,
    clock=time.monotonic,
) -> Unrestricted:
    """Retry/restart route for a task already pinned to a TorBox item.

    A missing item soft-recreates once from the original hoster URL and the
    queue is expected to persist the replacement `item_id` it gets back. An
    item that exists but isn't ready, or any auth/malformed-response
    failure, is raised as-is: only "missing" recreates.
    """
    token = getattr(settings, "torbox_api_token", "")
    if not isinstance(token, str) or not token.strip():
        raise DebridError(
            TORBOX, "missing_credential",
            "is needed for this download but has no API token saved. "
            "Add one in Settings.",
            False, False,
        )
    token = token.strip()
    entry = _torbox_mylist_entry(item_id, token, session=session)
    if entry is None:
        return torbox_unrestrict(hoster_url, token, session=session, sleep=sleep, clock=clock)
    if not (entry.get("download_present") is True or entry.get("download_finished") is True):
        raise DebridError(
            TORBOX, "not_ready",
            "this TorBox item is not ready yet.", False, False,
        )
    file_id, filename, filesize = _torbox_pick_file(entry.get("files"))
    download = _torbox_request_dl("webdl", item_id, file_id, token, session=session)
    return Unrestricted(
        download=download, filename=filename, filesize=filesize,
        provider=TORBOX, item_id=item_id,
    )


def _torbox_file_id_present(files, file_id: str) -> bool:
    """Whether `file_id` still names one of the torrent's current files.

    A stale persisted `file_id` (the torrent was re-checked/re-selected on
    TorBox's side since materialisation) must not be sent to requestdl as
    if it were still valid.
    """
    if not isinstance(files, list):
        return False
    try:
        target = _torbox_numeric_id(file_id, TORBOX)
    except DebridError:
        return False
    for f in files:
        if not isinstance(f, dict):
            continue
        try:
            if _torbox_numeric_id(f.get("id"), TORBOX) == target:
                return True
        except DebridError:
            continue
    return False


def torbox_refresh_torrent_file(item_id: str, file_id: str, token: str, *, session=None) -> str:
    """Relaunch path for an already-materialised TorBox torrent-file row.

    Unlike the hoster route there is no original request to soft-recreate
    from if TorBox no longer has the item -- selecting files again would
    need the user's original file choice, which the queue does not keep.
    A missing item, an item that is not ready, or a file_id that no longer
    appears in the torrent's current file list are therefore all fixed
    errors, never a silent recreate.
    """
    if not isinstance(token, str) or not token.strip():
        raise DebridError(
            TORBOX, "missing_credential",
            "is needed for this download but has no API token saved. "
            "Add one in Settings.",
            False, False,
        )
    token = token.strip()
    entry = _torbox_torrent_entry(item_id, token, session=session)
    if entry is None:
        raise DebridError(
            TORBOX, "missing_item",
            "this TorBox torrent is no longer in your account. "
            "Re-add it to fetch it again.",
            False, False,
        )
    if not (entry.get("download_present") is True or entry.get("download_finished") is True):
        raise DebridError(
            TORBOX, "not_ready",
            "this TorBox torrent is not ready yet.", False, False,
        )
    if not _torbox_file_id_present(entry.get("files"), file_id):
        raise DebridError(
            TORBOX, "missing_item",
            "this file is no longer part of this TorBox torrent. "
            "Re-add it to fetch it again.",
            False, False,
        )
    return _torbox_request_dl("torrents", item_id, file_id, token, session=session)


def _torbox_check_cached_torrent(info_hash: str, token: str, *, session=None) -> bool:
    resp = _request(
        session, "get",
        f"{TORBOX_BASE}/torrents/checkcached?hash={info_hash}&format=list",
        TORBOX, headers=_bearer(token),
    )
    data = _torbox_payload(resp)
    if isinstance(data, dict):
        return bool(data.get(info_hash))
    if isinstance(data, list):
        return len(data) > 0
    return False


def _torbox_create_torrent(
    info_hash: str, token: str, *, torrent_bytes: bytes | None, session=None,
) -> Optional[str]:
    """Create a torrent under the account, refusing anything not cached.

    `add_only_if_cached` is TorBox's own server-side guarantee for this
    endpoint (unlike webdl's createwebdownload, which has none). `seed`
    and `allow_zip` are sent as ordinary multipart fields, matching the
    rest of this module's TorBox requests, so that a whole-torrent zip or
    post-completion seeding is never silently opted into by a provider
    default.

    Returns None when TorBox reports nothing was created -- the
    checkcached probe was a false positive, and nothing needs cleaning up.
    """
    parts = {
        "seed": (None, "3"),
        "allow_zip": (None, "false"),
        "add_only_if_cached": (None, "true"),
    }
    if torrent_bytes is not None:
        parts["file"] = ("cove.torrent", torrent_bytes, "application/x-bittorrent")
    else:
        parts["magnet"] = (None, _torrent.minimal_magnet(info_hash))
    resp = _request(
        session, "post", f"{TORBOX_BASE}/torrents/createtorrent", TORBOX,
        headers=_bearer(token), files=parts,
    )
    data = _torbox_payload(resp)
    if not isinstance(data, dict):
        raise _bad_response(TORBOX)
    torrent_id = data.get("torrent_id")
    if torrent_id is None or isinstance(torrent_id, bool):
        return None
    return _torbox_numeric_id(torrent_id)


def _torbox_torrent_entry(item_id: str, token: str, *, session=None):
    """The mylist row for one torrent, or None when TorBox has no record
    of it (a missing item, not an error)."""
    safe_id = _torbox_numeric_id(item_id)
    resp = _request(
        session, "get", f"{TORBOX_BASE}/torrents/mylist?id={safe_id}", TORBOX,
        headers=_bearer(token),
    )
    data = _torbox_payload(resp)
    if data is None:
        return None
    if isinstance(data, list):
        data = data[0] if data else None
    if data is not None and not isinstance(data, dict):
        raise _bad_response(TORBOX)
    return data


def _torbox_delete_torrent(item_id: str, token: str, *, session=None) -> None:
    """Best-effort cleanup for a job Cove's own probe decided to abandon.

    Never allowed to raise: this only ever runs while another outcome is
    about to be returned, and a cleanup failure must not replace it.
    controltorrent takes a JSON body, unlike the rest of this module's
    form-encoded TorBox requests.
    """
    try:
        safe_id = _torbox_numeric_id(item_id)
        _request(
            session, "post", f"{TORBOX_BASE}/torrents/controltorrent", TORBOX,
            headers={**_bearer(token), "Content-Type": "application/json"},
            data=json.dumps({"torrent_id": int(safe_id), "operation": "delete"}),
        )
    except DebridError:
        pass


def _torbox_cached_files(entry: dict, name: str, torrent_id: str) -> tuple:
    raw_files = entry.get("files")
    if not isinstance(raw_files, list) or not raw_files:
        raise _bad_response(TORBOX)
    if len(raw_files) > _MAX_CACHED_FILES:
        raise _bad_response(TORBOX)
    seen_ids: set = set()
    out = []
    for index, f in enumerate(raw_files):
        if not isinstance(f, dict):
            raise _bad_response(TORBOX)
        # _torbox_numeric_id rejects bools, non-integral/non-finite floats,
        # and anything int()-unconvertible (None, empty string, ...) --
        # TorBox's own schema types file IDs as JSON numbers.
        file_id = _torbox_numeric_id(f.get("id"), TORBOX)
        if file_id in seen_ids:
            raise _bad_response(TORBOX)
        seen_ids.add(file_id)
        raw_path = f.get("name")
        if not isinstance(raw_path, str) or not raw_path:
            raw_path = f.get("short_name")
        if not isinstance(raw_path, str) or not raw_path:
            raise _bad_response(TORBOX)
        parts = tuple(
            _torrent_component(p, TORBOX)
            for p in raw_path.replace("\\", "/").split("/") if p
        )
        if not parts:
            raise DebridError(
                TORBOX, "unsafe_path",
                "returned a file path Cove will not write to.", False, False,
            )
        out.append(CachedTorrentFile(
            index=index,
            path=_strip_root(name, parts),
            size=_safe_filesize(f.get("size"), TORBOX),
            item_id=torrent_id,
            file_id=file_id,
        ))
    return tuple(out)


def torbox_cached_torrent(
    info_hash: str,
    token: str,
    *,
    torrent_bytes: bytes | None = None,
    session=None,
    sleep=time.sleep,
    clock=time.monotonic,
) -> Optional[CachedTorrent]:
    """Return the torrent's files if TorBox already has it cached, else None.

    Cached-only is enforced twice: Cove's own checkcached probe first, and
    then TorBox's own `add_only_if_cached=true` on createtorrent, which
    refuses to create anything that is not already cached. A created item
    that still never reports ready is a cache race, not something to wait
    out -- it is deleted and reported as not cached rather than left to
    become an active TorBox download.
    """
    info_hash = _torrent.normalize_info_hash(info_hash)
    if torrent_bytes is not None and len(torrent_bytes) > _torrent.MAX_TORRENT_BYTES:
        raise _bad_response(TORBOX)
    if not _torbox_check_cached_torrent(info_hash, token, session=session):
        return None
    torrent_id = _torbox_create_torrent(
        info_hash, token, torrent_bytes=torrent_bytes, session=session,
    )
    if torrent_id is None:
        # add_only_if_cached refused the create: nothing exists to clean up.
        return None
    keep = False
    try:
        deadline = clock() + TORBOX_READY_MAX_WAIT
        while True:
            entry = _torbox_torrent_entry(torrent_id, token, session=session)
            if entry is None:
                raise _bad_response(TORBOX)
            if entry.get("download_present") is True or entry.get("download_finished") is True:
                break
            if clock() >= deadline:
                return None
            sleep(TORBOX_READY_POLL_INTERVAL)
        name = _torrent_root_name(entry.get("name"), info_hash, TORBOX)
        files = _torbox_cached_files(entry, name, torrent_id)
        keep = True
        return CachedTorrent(TORBOX, info_hash, name, files)
    finally:
        if not keep:
            _torbox_delete_torrent(torrent_id, token, session=session)


# ---------------------------------------------------------------------------
# Host matching and the domain cache
# ---------------------------------------------------------------------------


def _normalize_domains(values) -> list[str]:
    out = []
    seen = set()
    for value in values:
        if not isinstance(value, str):
            continue
        domain = value.strip().lower().strip(".")
        if not domain or domain in seen:
            continue
        seen.add(domain)
        out.append(domain)
    return out


def _hostname(url) -> str:
    """Hostname of an http(s) URL, or "" for anything else.

    Parsing rather than string matching is the point here: it is what
    keeps `rapidgator.net.evil.com` and `?x=rapidgator.net` from matching.
    """
    if not isinstance(url, str) or not url:
        return ""
    try:
        parsed = urlparse(url)
    except ValueError:
        return ""
    if parsed.scheme.lower() not in ("http", "https"):
        return ""
    return (parsed.hostname or "").lower().strip(".")


def is_supported_domain(url, domains) -> bool:
    """Exact host match, or a subdomain on a dot boundary."""
    host = _hostname(url)
    if not host or not domains:
        return False
    for domain in domains:
        if not isinstance(domain, str):
            continue
        domain = domain.strip().lower().strip(".")
        if domain and (host == domain or host.endswith("." + domain)):
            return True
    return False


def is_provider_domain(url) -> bool:
    return is_supported_domain(url, PROVIDER_OWN_DOMAINS)


# Provider share / landing pages. These serve the file only to the browser
# session of the account that generated them, so Cove can neither fetch them
# directly (it gets the provider's "forbidden" HTML page) nor re-resolve them
# through the API (they are not hoster links).
#
# Generated node URLs are deliberately NOT listed here: a link like
# `s1.debrid.it/dl/...` or `45.download.real-debrid.com/d/...` is a plain
# direct URL that downloads fine when pasted by hand, and refusing those
# would break a legitimate manual workflow. Matching is anchored to the bare
# apex host plus the share path prefix so download subdomains fall through.
_SHARE_LINK_HOSTS = {
    "real-debrid.com": ("/d/", REAL_DEBRID),
    "alldebrid.com": ("/f/", ALL_DEBRID),
}


def share_link_reason(url) -> str:
    """Explain why an account-bound provider share link can't be downloaded.

    Returns "" for anything Cove should keep handling normally.
    """
    host = _hostname(url)
    if not host:
        return ""
    if host.startswith("www."):
        host = host[4:]
    entry = _SHARE_LINK_HOSTS.get(host)
    if entry is None:
        return ""
    prefix, provider = entry
    try:
        path = urlparse(url).path
    except ValueError:
        return ""
    if not path.startswith(prefix):
        return ""
    return (
        f"{provider_label(provider)} share links are tied to the account that "
        f"created them and can't be downloaded by Cove. Add the original "
        f"hoster link instead."
    )


def _cache_path() -> Path:
    from .config import DATA_DIR

    return Path(DATA_DIR) / HOST_CACHE_FILE


def _read_cache() -> dict:
    try:
        raw = json.loads(_cache_path().read_text())
    except (OSError, ValueError):
        return {}
    return raw if isinstance(raw, dict) else {}


def _cached_entry(cache: dict, provider: str):
    """Return (domains, fetched_at) for a usable entry, else (None, 0.0)."""
    entry = cache.get(provider)
    if not isinstance(entry, dict):
        return None, 0.0
    domains = entry.get("domains")
    if not isinstance(domains, list):
        return None, 0.0
    fetched_at = entry.get("fetched_at")
    if isinstance(fetched_at, bool) or not isinstance(fetched_at, (int, float)):
        fetched_at = 0.0
    return _normalize_domains(domains), float(fetched_at)


def _write_cache(provider: str, domains: list[str]) -> None:
    cache = _read_cache()
    cache[provider] = {"fetched_at": time.time(), "domains": domains}
    path = _cache_path()
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(cache))
        tmp.replace(path)
    except OSError:
        # A cache we cannot write is not worth failing a download over.
        pass


def supported_domains(provider: str, *, session=None, now=None) -> Optional[list[str]]:
    """Cached host list for a provider.

    Returns None when neither a cache nor a live fetch is available. The
    caller must read that as "unknown, treat the URL as a candidate" and
    let the resolve endpoint decide, rather than as "unsupported".
    """
    now = time.time() if now is None else now
    cached, fetched_at = _cached_entry(_read_cache(), provider)
    if cached is not None and 0 <= now - fetched_at < HOST_CACHE_TTL:
        return cached
    if provider == ALL_DEBRID:
        fetch = all_debrid_supported_domains
    elif provider == TORBOX:
        fetch = torbox_supported_domains
    else:
        fetch = real_debrid_supported_domains
    try:
        domains = fetch(session=session)
    except Exception:
        return cached  # stale list if we have one, else None
    _write_cache(provider, domains)
    return domains


# ---------------------------------------------------------------------------
# Shared resolver
# ---------------------------------------------------------------------------


def _preferred(settings) -> str:
    preferred = getattr(settings, "debrid_preferred_provider", DEBRID_DEFAULT_PROVIDER)
    return preferred if preferred in PROVIDERS else DEBRID_DEFAULT_PROVIDER


def _enabled_providers(settings) -> list[tuple[str, str]]:
    """(provider, credential) pairs, preferred provider first.

    Remaining providers keep DEBRID_PROVIDERS' registration order (a stable
    sort on "is this the preferred one" preserves relative order for ties),
    so appending a provider there is what puts it last in the fallback
    chain. TorBox additionally requires the internal feature-availability
    gate: while it is off, TorBox never enters this list regardless of the
    user's torbox_enabled setting, so existing two-provider ordering is
    unaffected.
    """
    pairs = []
    if getattr(settings, "all_debrid_enabled", False) is True:
        pairs.append((ALL_DEBRID, getattr(settings, "all_debrid_api_key", "")))
    if getattr(settings, "real_debrid_enabled", False) is True:
        pairs.append((REAL_DEBRID, getattr(settings, "real_debrid_api_token", "")))
    if TORBOX_FEATURE_AVAILABLE and getattr(settings, "torbox_enabled", False) is True:
        pairs.append((TORBOX, getattr(settings, "torbox_api_token", "")))
    preferred = _preferred(settings)
    pairs.sort(key=lambda pair: 0 if pair[0] == preferred else 1)
    return pairs


def is_enabled(settings) -> bool:
    """True when the user has switched on at least one provider.

    The queue uses this to decide whether an http(s) task must go through
    the resolving worker. It deliberately ignores whether a credential is
    present: an enabled provider with an empty key has to reach resolve()
    so the user gets the "no API key saved" error, rather than silently
    getting a free-tier download from the hoster instead.
    """
    return bool(_enabled_providers(settings))


def _unrestrict(provider: str, url: str, credential: str, *, session, sleep, clock):
    if provider == ALL_DEBRID:
        return all_debrid_unrestrict(
            url, credential, session=session, sleep=sleep, clock=clock
        )
    if provider == TORBOX:
        return torbox_unrestrict(url, credential, session=session, sleep=sleep, clock=clock)
    return real_debrid_unrestrict(url, credential, session=session)


def resolve(
    url: str,
    settings,
    *,
    session=None,
    sleep=time.sleep,
    clock=time.monotonic,
) -> Optional[Unrestricted]:
    """Resolve `url` through the configured providers.

    Returns None when debrid does not apply — nothing enabled, not an
    http(s) URL, a provider-owned URL, or no enabled provider supports the
    host. In every one of those cases Cove downloads the URL directly.

    Raises DebridError when a provider that should have handled the link
    failed in a way the user needs to know about.
    """
    if not _hostname(url) or is_provider_domain(url):
        return None
    providers = _enabled_providers(settings)
    if not providers:
        return None

    errors: list[DebridError] = []
    for provider, credential in providers:
        domains = supported_domains(provider, session=session)
        if domains is not None and not is_supported_domain(url, domains):
            # This provider publishes a host list and this host isn't on
            # it; don't spend a request asking.
            continue
        if not isinstance(credential, str) or not credential.strip():
            raise DebridError(
                provider, "missing_credential",
                "is enabled but has no API key saved. Add one in Settings.",
                False, False,
            )
        try:
            return _unrestrict(
                provider, url, credential.strip(),
                session=session, sleep=sleep, clock=clock,
            )
        except DebridError as exc:
            if not exc.fallback_allowed:
                raise
            errors.append(exc)

    if errors and not all(exc.host_unsupported for exc in errors):
        # Something recoverable-looking went wrong everywhere. Surface the
        # last reason rather than quietly downloading the free-tier page.
        raise errors[-1]
    return None


# ---------------------------------------------------------------------------
# Cached torrents
# ---------------------------------------------------------------------------
#
# A torrent a provider already holds can be downloaded as ordinary HTTPS
# files, which is the whole point of this route. Cove only ever *probes*:
# it never asks a provider to fetch a torrent it does not already have, and
# it deletes any entry its probe created. That keeps the user's provider
# account from filling up with torrents Cove decided not to use.
#
# Two things are deliberately never sent to a provider: the user's original
# magnet (it can carry a private-tracker passkey in `tr=`) and anything
# derived from it beyond the info hash.

# Real-Debrid resolves a magnet to metadata asynchronously. That conversion
# is the only wait Cove will sit through -- it is not the torrent being
# downloaded, it is the provider looking the torrent up.
RD_TORRENT_POLL_INTERVAL = 2.0
RD_TORRENT_MAX_WAIT = 15.0

# Real-Debrid states that mean the provider is (or would be) fetching the
# torrent itself. Seeing any of these means "not cached", full stop.
_RD_ACTIVE_STATES = frozenset({"queued", "downloading", "compressing", "uploading"})
_RD_DEAD_STATES = frozenset({"error", "virus", "dead", "magnet_error"})

_MAX_CACHED_FILES = 20_000
_MAX_TREE_DEPTH = 32


@dataclass
class CachedTorrentFile:
    """One file of a cached torrent.

    `locked_link` is AllDebrid/Real-Debrid's account-bound link. It is not
    a download URL: it has to be unlocked into a short-lived node URL
    first, exactly like a hoster link. Unlike the node URL it is stable,
    so it is what gets persisted.

    TorBox has no such per-file link: `item_id`/`file_id` identify the
    torrent and file instead, and requestdl regenerates a delivery URL
    from them on every launch. Exactly one of `locked_link` or the
    `item_id`/`file_id` pair is populated, depending on provider.
    """

    index: int
    path: tuple[str, ...]
    size: int
    locked_link: str = ""
    item_id: str = ""
    file_id: str = ""

    @property
    def relative_path(self) -> str:
        return "/".join(self.path)


@dataclass
class CachedTorrent:
    provider: str
    info_hash: str
    name: str
    files: tuple[CachedTorrentFile, ...]

    @property
    def multi_file(self) -> bool:
        return len(self.files) > 1 or any(len(f.path) > 1 for f in self.files)

    def destination_parts(self, file: CachedTorrentFile) -> tuple[str, ...]:
        """Path components for `file` below the chosen output directory."""
        return (self.name,) + file.path if self.multi_file else file.path


def _torrent_component(value, provider: str) -> str:
    """Validate one provider-supplied path component.

    The provider's file tree is untrusted for exactly the same reason the
    torrent's own is: it names files Cove is about to create.
    """
    try:
        return _torrent.safe_component(value)
    except _torrent.TorrentError:
        raise DebridError(
            provider, "unsafe_path",
            "returned a file path Cove will not write to.", False, False,
        ) from None


def _torrent_root_name(value, info_hash: str, provider: str) -> str:
    """Safe folder name for the torrent, falling back to its info hash.

    The hash is not a secret -- it is the public identity of the torrent
    and is already stored in the local database -- so it is a usable last
    resort when the provider's name can't be made safe.
    """
    try:
        return _torrent.safe_component(value)
    except _torrent.TorrentError:
        return info_hash


def _strip_root(name: str, parts: tuple[str, ...]) -> tuple[str, ...]:
    """Drop a leading folder that just repeats the torrent name.

    AllDebrid's tree roots a multi-file torrent under its own name; the
    queue adds that folder itself, so keeping it would nest twice.
    """
    if len(parts) > 1 and parts[0] == name:
        return parts[1:]
    return parts


# --- AllDebrid -------------------------------------------------------------


def _ad_delete_magnet(session, apikey: str, magnet_id) -> None:
    """Best-effort removal of a probe entry, with one retry.

    Never raises: a failure here must not mask the real outcome, and the
    caller has nothing useful to do about it. Nothing is logged, because
    the only things worth logging are the key and the entry id.
    """
    for attempt in (0, 1):
        try:
            _ad_call(session, "post", "/magnet/delete", apikey, {"id": magnet_id})
            return
        except DebridError as exc:
            # Retry once for a transport blip; a refusal will not get better.
            if attempt == 1 or exc.code != "transport":
                return


def _ad_entry(data: dict, key: str) -> dict:
    entries = data.get(key)
    if not isinstance(entries, list) or len(entries) != 1:
        raise _bad_response(ALL_DEBRID)
    entry = entries[0]
    if not isinstance(entry, dict):
        raise _bad_response(ALL_DEBRID)
    if entry.get("error"):
        error = entry["error"]
        code = error.get("code") if isinstance(error, dict) else None
        raise _error(ALL_DEBRID, code if isinstance(code, str) else None, _AD_ERRORS)
    return entry


def _ad_flatten(nodes, prefix: tuple[str, ...], out: list, depth: int) -> None:
    if depth > _MAX_TREE_DEPTH or not isinstance(nodes, list):
        raise _bad_response(ALL_DEBRID)
    for node in nodes:
        if not isinstance(node, dict):
            raise _bad_response(ALL_DEBRID)
        part = _torrent_component(node.get("n"), ALL_DEBRID)
        entries = node.get("e")
        if isinstance(entries, list):
            _ad_flatten(entries, prefix + (part,), out, depth + 1)
            continue
        link = node.get("l")
        if not isinstance(link, str) or not link:
            raise DebridError(
                ALL_DEBRID, "missing_link",
                "did not return a download link for one of this torrent's files.",
                False, False,
            )
        if len(out) >= _MAX_CACHED_FILES:
            raise _bad_response(ALL_DEBRID)
        out.append((
            prefix + (part,),
            _safe_filesize(node.get("s"), ALL_DEBRID),
            _safe_download_url(link, ALL_DEBRID),
        ))


def _ad_cached_files(session, apikey: str, magnet_id, name: str) -> tuple:
    data = _ad_call(session, "post", "/magnet/files", apikey, {"id[]": magnet_id})
    entry = _ad_entry(data, "magnets")
    flat: list = []
    _ad_flatten(entry.get("files"), (), flat, 0)
    if not flat:
        raise _bad_response(ALL_DEBRID)
    return tuple(
        CachedTorrentFile(
            index=index,
            path=_strip_root(name, parts),
            size=size,
            locked_link=link,
        )
        for index, (parts, size, link) in enumerate(flat)
    )


def all_debrid_cached_torrent(
    info_hash: str,
    apikey: str,
    *,
    torrent_bytes: bytes | None = None,
    session=None,
) -> Optional[CachedTorrent]:
    """Return the torrent's files if AllDebrid already has it, else None.

    An entry created by this probe is deleted unless it turns out to hold
    the cached files we are about to download from.
    """
    info_hash = _torrent.normalize_info_hash(info_hash)
    if torrent_bytes is not None:
        if len(torrent_bytes) > _torrent.MAX_TORRENT_BYTES:
            raise _bad_response(ALL_DEBRID)
        resp = _request(
            session, "post", f"{AD_BASE}/magnet/upload/file", ALL_DEBRID,
            headers=_bearer(apikey),
            files={"files[0]": ("cove.torrent", torrent_bytes, "application/x-bittorrent")},
        )
        entry = _ad_entry(_ad_data(resp), "files")
    else:
        data = _ad_call(
            session, "post", "/magnet/upload", apikey,
            {"magnets[]": _torrent.minimal_magnet(info_hash)},
        )
        entry = _ad_entry(data, "magnets")

    magnet_id = entry.get("id")
    if magnet_id is None:
        raise _bad_response(ALL_DEBRID)
    keep = False
    try:
        if entry.get("ready") is not True:
            # Not cached. Cove does not wait for AllDebrid to fetch it.
            return None
        name = _torrent_root_name(entry.get("name") or entry.get("filename"), info_hash, ALL_DEBRID)
        files = _ad_cached_files(session, apikey, magnet_id, name)
        keep = True
        return CachedTorrent(ALL_DEBRID, info_hash, name, files)
    finally:
        if not keep:
            _ad_delete_magnet(session, apikey, magnet_id)


# --- Real-Debrid -----------------------------------------------------------


def _rd_no_content(resp) -> None:
    """Accept a 2xx with no body; map an error envelope if there is one."""
    if 200 <= getattr(resp, "status_code", 0) < 300:
        return
    try:
        body = resp.json()
    except Exception:
        body = None
    if isinstance(body, dict) and ("error_code" in body or "error" in body):
        code = body.get("error_code")
        if not isinstance(code, int) or isinstance(code, bool):
            code = None
        raise _error(REAL_DEBRID, code, _RD_ERRORS)
    raise DebridError(REAL_DEBRID, "http", _TRANSPORT, True, False)


def _rd_delete_torrent(session, token: str, torrent_id) -> None:
    """Best-effort removal of a probe entry, with one retry. Never raises."""
    for attempt in (0, 1):
        try:
            resp = _request(
                session, "delete", f"{RD_BASE}/torrents/delete/{torrent_id}",
                REAL_DEBRID, headers=_bearer(token),
            )
            _rd_no_content(resp)
            return
        except DebridError as exc:
            if attempt == 1 or exc.code not in ("transport", "http"):
                return


def _rd_cached_files(info: dict, info_hash: str) -> tuple:
    name = _torrent_root_name(info.get("filename"), info_hash, REAL_DEBRID)
    raw_files = info.get("files")
    links = info.get("links")
    if not isinstance(raw_files, list) or not isinstance(links, list):
        raise _bad_response(REAL_DEBRID)
    selected = [f for f in raw_files if isinstance(f, dict) and f.get("selected")]
    if not selected or len(selected) != len(links):
        # links are positional against the selected files; a mismatch means
        # we cannot say which link belongs to which path.
        raise _bad_response(REAL_DEBRID)
    if len(selected) > _MAX_CACHED_FILES:
        raise _bad_response(REAL_DEBRID)
    out = []
    for index, (entry, link) in enumerate(zip(selected, links)):
        raw_path = entry.get("path")
        if not isinstance(raw_path, str) or not raw_path:
            raise _bad_response(REAL_DEBRID)
        parts = tuple(
            _torrent_component(p, REAL_DEBRID)
            for p in raw_path.split("/") if p
        )
        if not parts:
            raise DebridError(
                REAL_DEBRID, "unsafe_path",
                "returned a file path Cove will not write to.", False, False,
            )
        out.append(CachedTorrentFile(
            index=index,
            path=_strip_root(name, parts),
            size=_safe_filesize(entry.get("bytes"), REAL_DEBRID),
            locked_link=_safe_download_url(link, REAL_DEBRID),
        ))
    return name, tuple(out)


def real_debrid_cached_torrent(
    info_hash: str,
    token: str,
    *,
    torrent_bytes: bytes | None = None,
    session=None,
    sleep=time.sleep,
    clock=time.monotonic,
) -> Optional[CachedTorrent]:
    """Return the torrent's files if Real-Debrid already has it, else None.

    Real-Debrid has no cache-lookup endpoint, so the probe adds the torrent
    and reads its state. The only state Cove waits on is
    `magnet_conversion` (the provider resolving metadata). The moment an
    actual fetch state appears the answer is "not cached" -- waiting for a
    download to finish would be Cove sitting on a torrent for an hour and
    then calling it cached.
    """
    info_hash = _torrent.normalize_info_hash(info_hash)
    if torrent_bytes is not None:
        if len(torrent_bytes) > _torrent.MAX_TORRENT_BYTES:
            raise _bad_response(REAL_DEBRID)
        resp = _request(
            session, "put", f"{RD_BASE}/torrents/addTorrent", REAL_DEBRID,
            headers=_bearer(token), data=torrent_bytes,
        )
    else:
        resp = _request(
            session, "post", f"{RD_BASE}/torrents/addMagnet", REAL_DEBRID,
            headers=_bearer(token),
            data={"magnet": _torrent.minimal_magnet(info_hash)},
        )
    body = _rd_payload(resp)
    torrent_id = body.get("id") if isinstance(body, dict) else None
    if not torrent_id:
        raise _bad_response(REAL_DEBRID)

    keep = False
    try:
        deadline = clock() + RD_TORRENT_MAX_WAIT
        selected = False
        while True:
            info = _rd_payload(_request(
                session, "get", f"{RD_BASE}/torrents/info/{torrent_id}",
                REAL_DEBRID, headers=_bearer(token),
            ))
            if not isinstance(info, dict):
                raise _bad_response(REAL_DEBRID)
            status = info.get("status")
            if not isinstance(status, str):
                raise _bad_response(REAL_DEBRID)

            if status in _RD_ACTIVE_STATES or status in _RD_DEAD_STATES:
                # Provider would have to fetch it (or can't): not cached.
                return None
            if status == "downloaded":
                name, files = _rd_cached_files(info, info_hash)
                keep = True
                return CachedTorrent(REAL_DEBRID, info_hash, name, files)
            if status == "waiting_files_selection":
                if selected:
                    # Selecting twice would be a loop, not progress.
                    return None
                selected = True
                _rd_no_content(_request(
                    session, "post", f"{RD_BASE}/torrents/selectFiles/{torrent_id}",
                    REAL_DEBRID, headers=_bearer(token), data={"files": "all"},
                ))
                continue
            if status != "magnet_conversion":
                raise _bad_response(REAL_DEBRID)
            if clock() >= deadline:
                # Still converting. Treat as not cached rather than wait.
                return None
            sleep(RD_TORRENT_POLL_INTERVAL)
    finally:
        if not keep:
            _rd_delete_torrent(session, token, torrent_id)


# --- Shared torrent routing ------------------------------------------------


def _probe_cached(provider: str, info_hash: str, credential: str, *, torrent_bytes, session, sleep, clock):
    if provider == ALL_DEBRID:
        return all_debrid_cached_torrent(
            info_hash, credential, torrent_bytes=torrent_bytes, session=session
        )
    if provider == TORBOX:
        return torbox_cached_torrent(
            info_hash, credential, torrent_bytes=torrent_bytes,
            session=session, sleep=sleep, clock=clock,
        )
    return real_debrid_cached_torrent(
        info_hash, credential, torrent_bytes=torrent_bytes,
        session=session, sleep=sleep, clock=clock,
    )


def resolve_torrent(
    info_hash: str,
    settings,
    *,
    torrent_bytes: bytes | None = None,
    session=None,
    sleep=time.sleep,
    clock=time.monotonic,
) -> Optional[CachedTorrent]:
    """Ask each enabled provider, preferred first, whether it has this torrent.

    Returns the first cached hit, or None when no enabled provider has it.
    "Not cached" is an ordinary answer and moves on to the next provider; a
    credential or account failure is not, and is raised so the user finds
    out their key is wrong instead of silently getting no torrent support.
    """
    providers = _enabled_providers(settings)
    if not providers:
        return None

    errors: list[DebridError] = []
    for provider, credential in providers:
        if not isinstance(credential, str) or not credential.strip():
            raise DebridError(
                provider, "missing_credential",
                "is enabled but has no API key saved. Add one in Settings.",
                False, False,
            )
        try:
            found = _probe_cached(
                provider, info_hash, credential.strip(),
                torrent_bytes=torrent_bytes, session=session,
                sleep=sleep, clock=clock,
            )
        except DebridError as exc:
            if not exc.fallback_allowed:
                raise
            errors.append(exc)
            continue
        if found is not None:
            return found
    if errors:
        raise errors[-1]
    return None


def unlock_torrent_file(locked_link: str, provider: str, settings, *, session=None,
                        sleep=time.sleep, clock=time.monotonic) -> Unrestricted:
    """Turn a stored account-bound torrent link into a fresh node URL.

    This is the relaunch path for a materialised torrent file row. It is
    pinned to the provider that produced the link -- the other provider
    cannot unlock it -- so there is no fallback here. TorBox never reaches
    this function: it has no locked link to unlock, and is relaunched
    through `torbox_refresh_torrent_file` instead. `PROVIDERS` is not used
    for this check because it also lists TorBox, which -- unlike
    AllDebrid/Real-Debrid -- has no per-file credential lookup below.
    """
    if provider not in (ALL_DEBRID, REAL_DEBRID):
        raise DebridError(
            provider, "unknown_provider",
            "is no longer available for this download.", False, False,
        )
    credential = (
        getattr(settings, "all_debrid_api_key", "") if provider == ALL_DEBRID
        else getattr(settings, "real_debrid_api_token", "")
    )
    if not isinstance(credential, str) or not credential.strip():
        raise DebridError(
            provider, "missing_credential",
            "is needed for this torrent download but has no API key saved. "
            "Add one in Settings.",
            False, False,
        )
    return _unrestrict(
        provider, locked_link, credential.strip(),
        session=session, sleep=sleep, clock=clock,
    )
